### ISSUE TITLE
Validity cf pull request

### ISSUE THREAD

**Issue by mfournial** [jordanspooner/ic-first-year-notes#8]
$A_{1},A_{2},\dots,A_{n}\vDash B$ should be called argument as a valid formula is just $\vDash A$ for eg right? (cf paragraph validity)
Therefore in the definition of soundness and completeness, they could deserve to be changed

**Comment by jordanspooner** [comment]
That's just what it says in the notes. Who knows why? I don't go to college to learn, I go to remember PDF slides word for word. That's what college is all about, right?
